chore(ci) Created pipeline with Dockerfile, other files added and modified for project needs

diff --git a/.github/workflows/prod-ci-cd-pipeline.yml b/.github/workflows/prod-ci-cd-pipeline.yml
--- a/.github/workflows/prod-ci-cd-pipeline.yml
+++ b/.github/workflows/prod-ci-cd-pipeline.yml
@@ -174,23 +174,28 @@ jobs:
         run: |
           set -euo pipefail
 
+          # Health check
+          echo "Waiting for container to become healthy..."
+
           ATTEMPTS=10
-          SLEEP=3
+          SLEEP_TIME=3
 
           for i in $(seq 1 $ATTEMPTS); do
             if curl -fs http://localhost:$APP_PORT >/dev/null; then
-              echo "Health check passed"
-              exit 0
+              echo "Container is healthy"
+              break
             fi
 
-            echo "Attempt $i failed..."
-            sleep $SLEEP
+            echo "Attempt $i/$ATTEMPTS failed. Retrying in ${SLEEP_TIME}s..."
+            sleep $SLEEP_TIME
+
+            if [ "$i" -eq "$ATTEMPTS" ]; then
+              echo "ERROR: Container failed to respond on port $APP_PORT"
+              echo "Showing logs:"
+              docker logs $CONTAINER_NAME
+              exit 1
+            fi
           done
-
-          echo "ERROR: Health check failed"
-          docker logs $CONTAINER_NAME || true
-          exit 1
-
       # --------------------------
       # Cleanup
       # --------------------------
